spring:
  datasource:
    url: jdbc:sqlite:./data/devaulty-dev.db?foreign_keys=on
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      additional-exclude: static/**,jpackage/**,db/**
devaulty:
  dev:
    token: "dev-secret-token"