app:
  version: "0.1.6-alpha"

spring:
  application:
    name: backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 60000
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 20
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: ${PORT:0}
  jetty:
    threads:
      max: 10
      min: 2
      idle-timeout: 30s
